package Chapter3._4_Exceptions.ThrowCustomException;

public class CustomExceptionThrower {

    /**
     * This method should throw a CustomException.
     *
     * I recommend looking at the test case for a good example of try/catch block usage, as well.
     */
    public void throwCustomException(){

    }

}
